language: python
python:
  - "3.4"
  - "3.5"
  - "3.6"
# command to install dependencies
install:
  - pip3 install -r requirements.txt
  - pip3 install nose coverage
  - pip3 install coveralls
services:
  - mongodb
before_script:
  - sleep 15
script:
  - python3 setup.py nosetests --with-coverage --cover-package pymdict --verbosity=2
after_success:
  - coveralls